# Generated by Django 4.1 on 2022-10-03 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_customuser_password_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/general'),
            preserve_default=False,
        ),
    ]
